#!/usr/bin/env python
# -*- python -*-
#
# Copyright (C) 2008  Google, Inc. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

'''
Squish: The stupid bug tracker.

This file contains the startup code to find the main squish library and do some
basic command line parsing using optparse.
'''

import os
import os.path
import sys

DEVELOPMENT_MODE = True
if DEVELOPMENT_MODE == True:
  libpath = os.path.abspath(sys.argv[0])
  libpath = os.path.dirname(libpath)
  libpath = os.path.join(libpath, '../lib')

  sys.path.append(libpath)

import squish


def main():
  '''
  Mainline of the program.
  '''

  squish.progName = os.path.basename(sys.argv[0])

  if '-' in squish.progName:
    (squish.progName, command_name) = squish.progName.split('-')
  elif len(sys.argv) > 1:
    command_name = sys.argv[1]
  else:
    squish.showSquishUsage()
    sys.exit(1)

  if not command_name in squish.registeredcommand.commands.keys():
    print '%s is not a valid command.' % command_name
    squish.showSquishUsage()
    sys.exit(1)

  cmd = squish.registeredcommand.commands[command_name]()
  result = cmd.runCommand()

  sys.exit(result)


if __name__ == '__main__':
  main()
